/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.44
 * Generated at: 2017-07-02 22:40:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class SignIn_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/views/Header.jsp", Long.valueOf(1499030199542L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>Navbar Example</title>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\">\r\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body style=\"background-color:#f5cba7\">\r\n");
      out.write("<form action=\"gh\">\r\n");
      out.write("<!-- Starting The Navbar Code -->\r\n");
      out.write("<nav class=\"navbar navbar-inverse\">\r\n");
      out.write("<div class=\"container-fluid\">\r\n");
      out.write("\r\n");
      out.write("<div class=\"navbar-header\">\r\n");
      out.write("<a class=\"navbar-brand\" rel=\"home\" href=\"#\" title=\"The Exprssion of Pearl\">\r\n");
      out.write("                <img style=\"max-width:50px; margin-top: -7px;\"\r\n");
      out.write("                     src=\"E:\\New folder\\cma2.jpg\">\r\n");
      out.write("            </a>\r\n");
      out.write("<a class=\"navbar-brand\" href=\"Home.jsp\"></a>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<ul class=\"nav navbar-nav\">\r\n");
      out.write("<li class=\"active\"><a href=\"Home.jsp\"><span class=\"glyphicon glyphicon-home\"></span>Home</a></li>\r\n");
      out.write("<li><a href=\"AboutUs\">AboutUs</a></li>\r\n");
      out.write("<li><a href=\"displayProduct\">Products</a>\r\n");
      out.write("<li><a href=\"ContactUs\">ContactUs</a></li>\r\n");
      out.write(" <li class=\"dropdown\"><a href=\"#\" class=\"dropdown-toggle\" \r\n");
      out.write(" data-toggle=\"dropdown\" role=\"button\" aria-haspopup=\"true\" \r\n");
      out.write(" aria-expanded=\"false\">Categories <span class=\"caret\"></span></a>\r\n");
      out.write("          <ul class=\"dropdown-menu\">\r\n");
      out.write("            <li><a href=\"#\">Page 1</a></li>\r\n");
      out.write("            <li><a href=\"#\">Page 2</a></li>\r\n");
      out.write("            <li><a href=\"#\">Page 3</a></li>\r\n");
      out.write("          </ul></li>        \r\n");
      out.write("<div class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("<li><a href=\"SignIn\"><span class=\"glyphicon glyphicon-share\"></span>SignIn </a></li>\r\n");
      out.write("<li><a href=\"Register\"><span class=\"glyphicon glyphicon-user\"></span>SignUp </a></li>\r\n");
      out.write("\r\n");
      out.write("<!-- Search Button -->\r\n");
      out.write(" <p>\r\n");
      out.write("        <li><button type=\"button\" class=\"btn btn-default btn-sm\">\r\n");
      out.write("          <span class=\"glyphicon glyphicon-search\"></span>Search \r\n");
      out.write("        </button></li>\r\n");
      out.write("      </p>\r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("</div>\r\n");
      out.write("</ul>\r\n");
      out.write("</div>\r\n");
      out.write("</nav>\r\n");
      out.write("</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("<link href=\"//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\">\r\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div id=\"login-overlay\" class=\"modal-dialog\">\r\n");
      out.write("      <div class=\"modal-content\">\r\n");
      out.write("          <div class=\"modal-header\">\r\n");
      out.write("              <button type=\"button\" class=\"close\" data-dismiss=\"modal\"><span aria-hidden=\"true\">×</span><span class=\"sr-only\">Close</span></button>\r\n");
      out.write("              <h4 class=\"modal-title\" id=\"myModalLabel\">SignIn </h4>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"modal-body\">\r\n");
      out.write("              <div class=\"row\">\r\n");
      out.write("                  <div class=\"col-xs-6\">\r\n");
      out.write("                      <div class=\"well\">\r\n");
      out.write("                          <form id=\"loginForm\" method=\"POST\" action=\"/login/\" novalidate=\"novalidate\">\r\n");
      out.write("                              <div class=\"form-group\">\r\n");
      out.write("                                  <label for=\"username\" class=\"control-label\">Username</label>\r\n");
      out.write("                                  <input type=\"text\" class=\"form-control\" id=\"username\" name=\"username\" value=\"\" required=\"\" title=\"Please enter you username\" placeholder=\"example@gmail.com\">\r\n");
      out.write("                                  <span class=\"help-block\"></span>\r\n");
      out.write("                              </div>\r\n");
      out.write("                              <div class=\"form-group\">\r\n");
      out.write("                                  <label for=\"password\" class=\"control-label\">Password</label>\r\n");
      out.write("                                  <input type=\"password\" class=\"form-control\" id=\"password\" name=\"password\" value=\"\" required=\"\" title=\"Please enter your password\">\r\n");
      out.write("                                  <span class=\"help-block\"></span>\r\n");
      out.write("                              </div>\r\n");
      out.write("                              <div id=\"loginErrorMsg\" class=\"alert alert-error hide\">Wrong username or password</div>\r\n");
      out.write("                              <div class=\"checkbox\">\r\n");
      out.write("                                  <label>\r\n");
      out.write("                                      <input type=\"checkbox\" name=\"remember\" id=\"remember\"> Remember login\r\n");
      out.write("                                  </label>\r\n");
      out.write("                                  \r\n");
      out.write("                              </div>\r\n");
      out.write("                              <button href=\"Header\" type=\"submit\" class=\"btn btn-success btn-block\">Login</button>\r\n");
      out.write("                              \r\n");
      out.write("                          </form>\r\n");
      out.write("                      </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  \r\n");
      out.write("              </div>\r\n");
      out.write("          </div>\r\n");
      out.write("      </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  </body>\r\n");
      out.write("  </html>\r\n");
      out.write("  ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
